services:
  e2e:
    image: brickninja/e2e
    build:
      context: .
      dockerfile: e2e/Dockerfile
    restart: no
    environment:
      - BASE_URL=http://en.brickninja.docker:3000/

  web:
    environment:
      - BRICKNINJA_URL=brickninja.docker:3000
    networks:
      default:
        aliases:
          - brickninja.docker
          - de.brickninja.docker
          - en.brickninja.docker
          - es.brickninja.docker
          - fr.brickninja.docker
          - nl.brickninja.docker
