services:
  database-old:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=brickninja
      - POSTGRES_PASSWORD=brickninja
      - POSTGRES_DB=brickninja
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/database:/var/lib/postgresql/data