-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "minAge" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "released" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "year" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "minifigureCount" DROP DEFAULT,
ALTER COLUMN "pieceCount" DROP DEFAULT;
