apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brick.ninja

commonLabels:
  app.kubernetes.io/part-of: brick.ninja

resources:
- ../base
- next
- database

images:
- name: ghcr.io/brickninja-org/brick.ninja/web
  newTag: latest
  newName: brick.ninja/web

- name: ghcr.io/brickninja-org/brick.ninja/worker
  newTag: latest
  newName: brick.ninja/worker

- name: ghcr.io/brickninja-org/brick.ninja/database-migration
  newTag: latest
  newName: brick.ninja/database-migration