apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brickninja

commonLabels:
  app.kubernetes.io/part-of: brickninja

resources:
- namespace.yaml
- database
- next
- worker
- database-migration